# Generated by Django 4.2.13 on 2024-07-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('greeting', models.CharField(max_length=500)),
            ],
        ),
    ]
